// 高度専門職ポイント計算表（docs/official/points-calculation-table_930001673.xlsx）の、チェック欄（□）の一覧。
// シート（A＝1号イ、B＝1号ロ、C＝1号ハ）の「AF列のロック解除セル」から生成した（Issue #186）。様式が改正されたら、再生成して、試験（hspPoint.test.ts）で照合する。
// points は、様式に印字された点数。印字がない・複数項目の組み合わせで決まるもの（研究実績の2つ以上など）は null。

export type HspPointSheetKey = "A" | "B" | "C";

export interface HspPointRow {
  /** シート上の行番号（チェック欄は、AF 列） */
  row: number;
  section: string;
  label: string;
  points: number | null;
  /** 疎明資料の番号（様式の記載。空は、直前の項目と共通） */
  evidence: string;
}

export const HSP_POINT_SHEETS: Record<HspPointSheetKey, { sheetName: string; label: string; rows: HspPointRow[] }> = {
  A: {
    sheetName: "A 高度専門職第１号イ",
    label: "高度専門職1号イ",
    rows: [
      { row: 14, section: "学歴", label: "博士学位（専門職学位を除く）", points: 30, evidence: "①" },
      { row: 15, section: "学歴", label: "修士又は専門職学位", points: 20, evidence: "" },
      { row: 16, section: "学歴", label: "大卒又はこれと同等以上の教育（博士，修士を除く）", points: 10, evidence: "" },
      { row: 17, section: "学歴", label: "複数の分野における２以上の博士若しくは修士の学位又は専門職学位（注２）", points: 5, evidence: "" },
      { row: 20, section: "職歴", label: "７年以上", points: 15, evidence: "" },
      { row: 21, section: "職歴", label: "５年以上７年未満", points: 10, evidence: "" },
      { row: 22, section: "職歴", label: "３年以上５年未満", points: 5, evidence: "" },
      { row: 24, section: "年収", label: "1,000万円以上", points: 40, evidence: "" },
      { row: 25, section: "年収", label: "900万円以上 1,000万円未満", points: 35, evidence: "" },
      { row: 26, section: "年収", label: "800万円以上 900万円未満", points: 30, evidence: "" },
      { row: 27, section: "年収", label: "700万円以上 800万円未満", points: 25, evidence: "" },
      { row: 28, section: "年収", label: "600万円以上 700万円未満", points: 20, evidence: "" },
      { row: 29, section: "年収", label: "500万円以上 600万円未満", points: 15, evidence: "" },
      { row: 30, section: "年収", label: "400万円以上 500万円未満", points: 10, evidence: "" },
      { row: 32, section: "年齢", label: "30歳未満", points: 15, evidence: "" },
      { row: 33, section: "年齢", label: "30～34歳", points: 10, evidence: "" },
      { row: 34, section: "年齢", label: "35～39歳", points: 5, evidence: "" },
      { row: 35, section: "研究", label: "発明者として特許を受けた発明が１件以上", points: 20, evidence: "④" },
      { row: 37, section: "研究", label: "外国政府から補助金，競争的資金等を受けた研究に３回以上従事", points: null, evidence: "⑤" },
      { row: 39, section: "研究", label: "学術論文データベース登載の学術雑誌の論文が3本以上（責任著者又は筆頭著者のものに限る）", points: null, evidence: "⑥" },
      { row: 41, section: "研究", label: "その他法務大臣が認める研究実績", points: 25, evidence: "⑦" },
      { row: 45, section: "特別加算", label: "Ⅰ イノベーション促進支援措置を受けている", points: 10, evidence: "⑨" },
      { row: 47, section: "特別加算", label: "Ⅱ Ⅰに該当する企業であって，中小企業基本法に規定する中小企業者", points: 10, evidence: "⑩" },
      { row: 49, section: "特別加算", label: "Ⅲ 産業の国際競争力強化等のため、地方公共団体における高度人材外国人の受入れ促進の支援措置（法務大臣が認めるもの）を受けている", points: 10, evidence: "⑪" },
      { row: 51, section: "特別加算", label: "中小企業者で、試験研究費及び開発費の合計額が売上高の3％超", points: 5, evidence: "⑩ ⑫" },
      { row: 59, section: "特別加算", label: "従事しようとする業務に関連する外国の資格，表彰等で法務大臣が認めるものを保有", points: 5, evidence: "⑬" },
      { row: 61, section: "特別加算", label: "日本の大学を卒業又は大学院の課程を修了", points: 10, evidence: "⑭" },
      { row: 65, section: "特別加算", label: "Ⅰ 日本語専攻で外国の大学を卒業又は日本語能力試験N1合格相当", points: 15, evidence: "" },
      { row: 67, section: "特別加算", label: "Ⅱ 日本語能力試験N2合格相当（日本の大学卒業・大学院修了及びⅠに該当する者を除く）", points: 10, evidence: "" },
      { row: 69, section: "特別加算", label: "各省が関与する成長分野の先端プロジェクトに従事", points: 10, evidence: "⑯" },
      { row: 73, section: "特別加算", label: "Ⅰ 大学ランキング2つ以上で300位以内の外国の大学又はランク付けされた本邦の大学を卒業", points: 10, evidence: "" },
      { row: 77, section: "特別加算", label: "Ⅱ スーパーグローバル大学創成支援事業（トップ型・グローバル化牽引型）の補助金交付大学を卒業", points: null, evidence: "" },
      { row: 79, section: "特別加算", label: "Ⅲ イノベーティブ・アジア事業のパートナー校を卒業", points: null, evidence: "" },
      { row: 82, section: "特別加算", label: "イノベーティブ・アジア事業の一環としてJICAが実施する研修を修了", points: 5, evidence: "⑱" },
    ],
  },
  B: {
    sheetName: "B 高度専門職第１号ロ",
    label: "高度専門職1号ロ",
    rows: [
      { row: 13, section: "学歴", label: "博士学位（専門職学位を除く）", points: 30, evidence: "①" },
      { row: 14, section: "学歴", label: "経営管理に関する専門職学位（MBA，MOT）を保有", points: 25, evidence: "" },
      { row: 15, section: "学歴", label: "修士又は専門職学位", points: 20, evidence: "" },
      { row: 16, section: "学歴", label: "大卒又はこれと同等以上の教育（博士，修士を除く）", points: 10, evidence: "" },
      { row: 17, section: "学歴", label: "複数の分野における２以上の博士若しくは修士の学位又は専門職学位（注２）", points: 5, evidence: "" },
      { row: 20, section: "職歴", label: "１０年以上", points: 20, evidence: "" },
      { row: 21, section: "職歴", label: "７年以上１０年未満", points: 15, evidence: "" },
      { row: 22, section: "職歴", label: "５年以上７年未満", points: 10, evidence: "" },
      { row: 23, section: "職歴", label: "３年以上５年未満", points: 5, evidence: "" },
      { row: 25, section: "年収", label: "1,000万円以上", points: 40, evidence: "" },
      { row: 26, section: "年収", label: "900万円以上 1,000万円未満", points: 35, evidence: "" },
      { row: 27, section: "年収", label: "800万円以上 900万円未満", points: 30, evidence: "" },
      { row: 28, section: "年収", label: "700万円以上 800万円未満", points: 25, evidence: "" },
      { row: 29, section: "年収", label: "600万円以上 700万円未満", points: 20, evidence: "" },
      { row: 30, section: "年収", label: "500万円以上 600万円未満", points: 15, evidence: "" },
      { row: 31, section: "年収", label: "400万円以上 500万円未満", points: 10, evidence: "" },
      { row: 35, section: "年齢", label: "30歳未満", points: 15, evidence: "" },
      { row: 36, section: "年齢", label: "30～34歳", points: 10, evidence: "" },
      { row: 37, section: "年齢", label: "35～39歳", points: 5, evidence: "" },
      { row: 38, section: "研究", label: "発明者として特許を受けた発明が１件以上", points: 15, evidence: "④" },
      { row: 40, section: "研究", label: "外国政府から補助金，競争的資金等を受けた研究に３回以上従事", points: null, evidence: "⑤" },
      { row: 42, section: "研究", label: "学術論文データベース登載の学術雑誌の論文が3本以上（責任著者又は筆頭著者のものに限る）", points: null, evidence: "⑥" },
      { row: 44, section: "研究", label: "その他法務大臣が認める研究実績", points: null, evidence: "⑦" },
      { row: 52, section: "特別加算", label: "Ⅰ イノベーション促進支援措置を受けている", points: 10, evidence: "⑨" },
      { row: 54, section: "特別加算", label: "Ⅱ Ⅰに該当する企業であって，中小企業基本法に規定する中小企業者", points: 10, evidence: "⑩" },
      { row: 56, section: "特別加算", label: "Ⅲ 産業の国際競争力強化等のため、地方公共団体における高度人材外国人の受入れ促進の支援措置（法務大臣が認めるもの）を受けている", points: 10, evidence: "⑪" },
      { row: 58, section: "特別加算", label: "中小企業者で、試験研究費及び開発費の合計額が売上高の3％超", points: 5, evidence: "⑩ ⑫" },
      { row: 66, section: "特別加算", label: "従事しようとする業務に関連する外国の資格，表彰等で法務大臣が認めるものを保有", points: 5, evidence: "⑬" },
      { row: 68, section: "特別加算", label: "日本の大学を卒業又は大学院の課程を修了", points: 10, evidence: "⑭" },
      { row: 72, section: "特別加算", label: "Ⅰ 日本語専攻で外国の大学を卒業又は日本語能力試験N1合格相当", points: 15, evidence: "" },
      { row: 74, section: "特別加算", label: "Ⅱ 日本語能力試験N2合格相当（日本の大学卒業・大学院修了及びⅠに該当する者を除く）", points: 10, evidence: "" },
      { row: 76, section: "特別加算", label: "各省が関与する成長分野の先端プロジェクトに従事", points: 10, evidence: "⑯" },
      { row: 80, section: "特別加算", label: "Ⅰ 大学ランキング2つ以上で300位以内の外国の大学又はランク付けされた本邦の大学を卒業", points: 10, evidence: "" },
      { row: 84, section: "特別加算", label: "Ⅱ スーパーグローバル大学創成支援事業（トップ型・グローバル化牽引型）の補助金交付大学を卒業", points: null, evidence: "" },
      { row: 86, section: "特別加算", label: "Ⅲ イノベーティブ・アジア事業のパートナー校を卒業", points: null, evidence: "" },
      { row: 89, section: "特別加算", label: "イノベーティブ・アジア事業の一環としてJICAが実施する研修を修了", points: 5, evidence: "⑱" },
    ],
  },
  C: {
    sheetName: "C 高度専門職１号ハ",
    label: "高度専門職1号ハ",
    rows: [
      { row: 14, section: "学歴", label: "経営管理に関する専門職学位（MBA，MOT）を保有", points: 25, evidence: "①" },
      { row: 15, section: "学歴", label: "博士若しくは修士の学位又は専門職学位", points: 20, evidence: "" },
      { row: 16, section: "学歴", label: "大卒又はこれと同等以上の教育（博士，修士を除く）", points: 10, evidence: "" },
      { row: 17, section: "学歴", label: "複数の分野における２以上の博士若しくは修士の学位又は専門職学位（注２）", points: 5, evidence: "" },
      { row: 20, section: "職歴", label: "１０年以上", points: 25, evidence: "" },
      { row: 21, section: "職歴", label: "７年以上１０年未満", points: 20, evidence: "" },
      { row: 22, section: "職歴", label: "５年以上７年未満", points: 15, evidence: "" },
      { row: 23, section: "職歴", label: "３年以上５年未満", points: 10, evidence: "" },
      { row: 24, section: "年収", label: "3,000万円以上", points: 50, evidence: "③" },
      { row: 25, section: "年収", label: "2,500万円以上 3,000万円未満", points: 40, evidence: "" },
      { row: 26, section: "年収", label: "2,000万円以上 2,500万円未満", points: 30, evidence: "" },
      { row: 27, section: "年収", label: "1,500万円以上 2,000万円未満", points: 20, evidence: "" },
      { row: 28, section: "年収", label: "1,000万円以上 1,500万円未満", points: 10, evidence: "" },
      { row: 31, section: "地位", label: "代表取締役，代表執行役又は代表権のある業務執行社員", points: 10, evidence: "⑳" },
      { row: 33, section: "地位", label: "取締役，執行役又は業務執行社員", points: 5, evidence: "" },
      { row: 37, section: "特別加算", label: "Ⅰ イノベーション促進支援措置を受けている", points: 10, evidence: "⑨" },
      { row: 39, section: "特別加算", label: "Ⅱ Ⅰに該当する企業であって，中小企業基本法に規定する中小企業者", points: 10, evidence: "⑩" },
      { row: 41, section: "特別加算", label: "Ⅲ 産業の国際競争力強化等のため、地方公共団体における高度人材外国人の受入れ促進の支援措置（法務大臣が認めるもの）を受けている", points: 10, evidence: "⑪" },
      { row: 43, section: "特別加算", label: "中小企業者で、試験研究費及び開発費の合計額が売上高の3％超", points: 5, evidence: "⑩ ⑫" },
      { row: 51, section: "特別加算", label: "従事しようとする業務に関連する外国の資格，表彰等で法務大臣が認めるものを保有", points: 5, evidence: "⑬" },
      { row: 53, section: "特別加算", label: "日本の大学を卒業又は大学院の課程を修了", points: 10, evidence: "⑭" },
      { row: 57, section: "特別加算", label: "Ⅰ 日本語専攻で外国の大学を卒業又は日本語能力試験N1合格相当", points: 15, evidence: "" },
      { row: 59, section: "特別加算", label: "Ⅱ 日本語能力試験N2合格相当（日本の大学卒業・大学院修了及びⅠに該当する者を除く）", points: 10, evidence: "" },
      { row: 61, section: "特別加算", label: "各省が関与する成長分野の先端プロジェクトに従事", points: 10, evidence: "⑯" },
      { row: 65, section: "特別加算", label: "Ⅰ 大学ランキング2つ以上で300位以内の外国の大学又はランク付けされた本邦の大学を卒業", points: 10, evidence: "" },
      { row: 69, section: "特別加算", label: "Ⅱ スーパーグローバル大学創成支援事業（トップ型・グローバル化牽引型）の補助金交付大学を卒業", points: null, evidence: "" },
      { row: 71, section: "特別加算", label: "Ⅲ イノベーティブ・アジア事業のパートナー校を卒業", points: null, evidence: "" },
      { row: 74, section: "特別加算", label: "イノベーティブ・アジア事業の一環としてJICAが実施する研修を修了", points: 5, evidence: "⑱" },
      { row: 80, section: "特別加算", label: "本邦の公私の機関において行う貿易その他の事業に１億円以上を投資", points: 5, evidence: "⑲" },
      { row: 81, section: "特別加算", label: "投資運用業等に係る業務に従事", points: 10, evidence: "㉑" },
    ],
  },
};
